// Generated by scripts/build-preload.mjs. Edit preload-source.cjs instead.
"use strict";
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// electron/ipc/channels.cjs
var require_channels = __commonJS({
  "electron/ipc/channels.cjs"(exports2, module2) {
    "use strict";
    module2.exports = Object.freeze({
      connectionsList: "connections:list",
      connectionsSave: "connections:save",
      connectionsRemove: "connections:remove",
      credentialsStatus: "credentials:status",
      credentialsRemove: "credentials:remove",
      hostKeysProbe: "host-keys:probe",
      hostKeysAccept: "host-keys:accept",
      sshConnect: "ssh:connect",
      sshDisconnect: "ssh:disconnect",
      terminalAttach: "terminal:attach",
      terminalWrite: "terminal:write",
      terminalResize: "terminal:resize",
      clipboardReadText: "clipboard:read-text",
      clipboardWriteText: "clipboard:write-text",
      sftpList: "sftp:list",
      sftpUpload: "sftp:upload",
      sftpCancel: "sftp:cancel",
      sftpRetry: "sftp:retry",
      monitorSample: "monitor:sample",
      updatesStatus: "updates:status",
      updatesCheck: "updates:check",
      updatesInstall: "updates:install",
      terminalData: "event:terminal-data",
      sessionState: "event:session-state",
      transferProgress: "event:transfer-progress",
      updateStatus: "event:update-status"
    });
  }
});

// electron/preload-source.cjs
var { contextBridge, ipcRenderer, webUtils } = require("electron");
var channels = require_channels();
function invoke(channel, payload) {
  return ipcRenderer.invoke(channel, payload);
}
function subscribe(channel, callback) {
  if (typeof callback !== "function") throw new TypeError("\u4E8B\u4EF6\u8BA2\u9605\u5FC5\u987B\u63D0\u4F9B\u56DE\u8C03\u51FD\u6570");
  const listener = (_event, payload) => callback(payload);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
}
function prepareLocalFiles(files) {
  const values = Array.from(files || []);
  const result = [];
  for (const file of values) {
    const localPath = webUtils.getPathForFile(file);
    if (!localPath) {
      return {
        ok: false,
        error: { code: "LOCAL_FILE_PATH_UNAVAILABLE", message: "\u65E0\u6CD5\u8BFB\u53D6\u8BE5\u672C\u5730\u6587\u4EF6\u7684\u78C1\u76D8\u8DEF\u5F84\u3002" }
      };
    }
    result.push({ localPath });
  }
  return { ok: true, files: result };
}
var api = Object.freeze({
  runtime: Object.freeze({ kind: "electron", version: 1 }),
  connections: Object.freeze({
    list: () => invoke(channels.connectionsList),
    save: (connection) => invoke(channels.connectionsSave, connection),
    remove: (connectionId) => invoke(channels.connectionsRemove, { connectionId })
  }),
  credentials: Object.freeze({
    status: () => invoke(channels.credentialsStatus),
    remove: (connectionId) => invoke(channels.credentialsRemove, { connectionId })
  }),
  hostKeys: Object.freeze({
    probe: (connectionId) => invoke(channels.hostKeysProbe, { connectionId }),
    accept: (challengeId) => invoke(channels.hostKeysAccept, { challengeId })
  }),
  ssh: Object.freeze({
    connect: (payload) => invoke(channels.sshConnect, payload),
    disconnect: (sessionId) => invoke(channels.sshDisconnect, { sessionId })
  }),
  terminal: Object.freeze({
    attach: (sessionId) => invoke(channels.terminalAttach, { sessionId }),
    write: (sessionId, data) => invoke(channels.terminalWrite, { sessionId, data }),
    resize: (sessionId, dimensions) => invoke(channels.terminalResize, { sessionId, ...dimensions })
  }),
  clipboard: Object.freeze({
    readText: () => invoke(channels.clipboardReadText),
    writeText: (text) => invoke(channels.clipboardWriteText, { text })
  }),
  sftp: Object.freeze({
    list: (sessionId, remotePath) => invoke(channels.sftpList, { sessionId, path: remotePath }),
    upload: (sessionId, remoteDirectory, files) => {
      const prepared = prepareLocalFiles(files);
      if (!prepared.ok) return Promise.resolve(prepared);
      return invoke(channels.sftpUpload, { sessionId, remoteDirectory, files: prepared.files });
    },
    cancel: (transferId) => invoke(channels.sftpCancel, { transferId }),
    retry: (transferId) => invoke(channels.sftpRetry, { transferId })
  }),
  monitor: Object.freeze({
    sample: (sessionId) => invoke(channels.monitorSample, { sessionId })
  }),
  updates: Object.freeze({
    status: () => invoke(channels.updatesStatus),
    check: () => invoke(channels.updatesCheck),
    install: () => invoke(channels.updatesInstall)
  }),
  events: Object.freeze({
    onTerminalData: (callback) => subscribe(channels.terminalData, callback),
    onSessionState: (callback) => subscribe(channels.sessionState, callback),
    onTransferProgress: (callback) => subscribe(channels.transferProgress, callback),
    onUpdateStatus: (callback) => subscribe(channels.updateStatus, callback)
  })
});
contextBridge.exposeInMainWorld("remoteTerminal", api);
