import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

await build({
  entryPoints: [path.join(projectRoot, "electron", "preload-source.cjs")],
  outfile: path.join(projectRoot, "electron", "preload.cjs"),
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node24",
  external: ["electron"],
  legalComments: "none",
  logLevel: "info",
  banner: { js: "// Generated by scripts/build-preload.mjs. Edit preload-source.cjs instead." },
});
