"use strict";

module.exports = Object.freeze({
  connectionsList: "connections:list",
  connectionsSave: "connections:save",
  connectionsRemove: "connections:remove",
  credentialsStatus: "credentials:status",
  credentialsRemove: "credentials:remove",
  hostKeysProbe: "host-keys:probe",
  hostKeysAccept: "host-keys:accept",
  sshConnect: "ssh:connect",
  sshDisconnect: "ssh:disconnect",
  terminalAttach: "terminal:attach",
  terminalWrite: "terminal:write",
  terminalResize: "terminal:resize",
  clipboardReadText: "clipboard:read-text",
  clipboardWriteText: "clipboard:write-text",
  sftpList: "sftp:list",
  sftpUpload: "sftp:upload",
  sftpCancel: "sftp:cancel",
  sftpRetry: "sftp:retry",
  monitorSample: "monitor:sample",
  updatesStatus: "updates:status",
  updatesCheck: "updates:check",
  updatesInstall: "updates:install",
  terminalData: "event:terminal-data",
  sessionState: "event:session-state",
  transferProgress: "event:transfer-progress",
  updateStatus: "event:update-status",
});
